'use client';
import {useState,useEffect} from 'react';
import GoogleSignIn from './GoogleSignIn';
import ForgotPassword from './ForgotPassword';
import {api} from './common';
export default function AccountSettings({user,setUser,setCode,setNotice}){
 const [busy,setBusy]=useState(false),[pending,setPending]=useState(null),[sessions,setSessions]=useState([]),[settingPassword,setSettingPassword]=useState(false);
 const refresh=()=>api('account/sessions').then(setSessions).catch(e=>setNotice(e.message));
 useEffect(()=>{refresh()},[]);
 async function action(e,route){e.preventDefault();const form=e.currentTarget;const data=Object.fromEntries(new FormData(form));setBusy(true);try{
  if(route==='account/password'&&data.password!==data.confirmPassword)throw Error('The new passwords do not match.');
  const d=await api(route,route==='account/email'?{...pending,...data}:data);
  if(route==='account/email-code'){setPending({...data,challenge:d.challenge});setNotice('Check your new email address for the verification code.');return}
  if(d.user)setUser(d.user);if(d.recoveryCode)setCode(d.recoveryCode);setNotice(route==='account/password'?'Password changed. Other sessions signed out. Save your new recovery code.':route==='account/email'?'Email updated and verified. Other sessions signed out.':'Profile updated.');form.reset();setPending(null);refresh();
 }catch(e){setNotice(e.message)}finally{setBusy(false)}}
 return <div className="account-settings">
 <section><span className="overline">01 / PROFILE</span><h3>Your details</h3><form onSubmit={e=>action(e,'account/profile')}><label>Display name<input name="name" defaultValue={user.name} required minLength={2} maxLength={60} autoComplete="name"/></label><button className="secondary" disabled={busy}>Save profile</button></form></section>
 <section><span className="overline">02 / SECURITY</span><h3>{user.has_password?'Change password':'Set a password'}</h3>{!user.has_password?<>{settingPassword?<ForgotPassword setNotice={setNotice} onBack={()=>setSettingPassword(false)} onDone={d=>{setUser(d.user);setCode(d.recoveryCode||'');setSettingPassword(false);refresh()}}/>:<><p>You currently sign in with Google. Verify your email to add a password.</p><button className="secondary" onClick={()=>setSettingPassword(true)}>Set password by email</button></>}</>:<form onSubmit={e=>action(e,'account/password')}><label>Current password<input name="currentPassword" type="password" autoComplete="current-password" required maxLength={128}/></label><label>New password<input name="password" type="password" autoComplete="new-password" minLength={10} maxLength={128} required/></label><label>Confirm new password<input name="confirmPassword" type="password" autoComplete="new-password" minLength={10} maxLength={128} required/></label><p className="micro-note">Other sessions will be signed out. Your private recovery code will also change.</p><button className="secondary" disabled={busy}>Update password</button></form>}</section>
 <section><span className="overline">03 / EMAIL ADDRESS</span><h3>Change email</h3><p className="account-email">{user.email} {user.email_verified?'· Verified':''}</p>{pending?<form onSubmit={e=>action(e,'account/email')}><label>Code sent to {pending.email}<input name="emailCode" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} required/></label><button className="primary" disabled={busy}>Verify new email</button><button type="button" className="secondary" disabled={busy} onClick={async()=>{setBusy(true);try{const d=await api('account/email-code',pending);setPending({...pending,challenge:d.challenge});setNotice('New code sent.')}catch(e){setNotice(e.message)}finally{setBusy(false)}}}>Resend code</button><button type="button" className="secondary" onClick={()=>setPending(null)}>Cancel</button></form>:<form onSubmit={e=>action(e,'account/email-code')}><label>New email address<input name="email" type="email" autoComplete="email" maxLength={180} required/></label><label>Current password<input name="currentPassword" type="password" autoComplete="current-password" required maxLength={128}/></label><p className="micro-note">Your email stays unchanged until you verify the new address. Changing it disconnects Google sign-in; you can reconnect afterward.</p><button className="secondary" disabled={busy}>Send verification code</button></form>}</section>
 <section><span className="overline">GOOGLE SIGN-IN</span><h3>{user.google_connected?'Google connected':'Connect your Google account'}</h3>{user.google_connected?<p>You can sign in with your connected Google account.</p>:user.has_password?<GoogleSignIn link/>:<p>Set a password first to connect an existing account.</p>}</section>
 <section><span className="overline">04 / ACTIVE SESSIONS</span><h3>Where you’re signed in</h3><p className="micro-note">Review sign-in times and remove access from other sessions.</p>{sessions.map(s=><div className="account-session" key={s.id}><div><strong>{s.current?'This session':'Other session'}</strong><span>Started {new Date(s.created).toLocaleString()}</span><span>Expires {new Date(s.expires).toLocaleString()}</span></div>{!s.current&&<button className="secondary" disabled={busy} onClick={async()=>{setBusy(true);try{await api('account/sessions/revoke',{id:s.id});await refresh();setNotice('Session signed out.')}catch(e){setNotice(e.message)}finally{setBusy(false)}}}>Sign out</button>}</div>)}<button className="secondary" disabled={busy||sessions.length<2} onClick={async()=>{setBusy(true);try{await api('account/sessions/revoke',{id:'others'});await refresh();setNotice('All other sessions signed out.')}catch(e){setNotice(e.message)}finally{setBusy(false)}}}>Sign out all other sessions</button></section>
 </div>
}
