'use client';
import Link from 'next/link';
import {useState} from 'react';
const steps=[
  {name:'The idea',label:'01 / A BRIEF IN YOUR WORDS',title:'Give your curiosity\na direction.',body:'Watch Bitcoin on 15-minute candles. Buy when RSI crosses back above 30. Keep each order under 100 USDT.',foot:'An example brief. Your mission starts with your own idea.'},
  {name:'The rules',label:'02 / NOTHING BETWEEN THE LINES',title:'See what your\nagent understood.',body:'Bitcoin · 15-minute candles',foot:'Review and edit the supported rules before activating a mission.'},
  {name:'The reasoning',label:'03 / FOLLOW THE DECISION',title:'Every move.\nAn explanation.',body:'Entry condition not met.',foot:'Illustrative decision trace — not a live signal or a performance claim.'}
];
export default function MissionShowcase(){const [active,setActive]=useState(0);const step=steps[active];return <section id="insights" className="mission-story reveal"><div className="mission-story-heading"><span className="section-index">03 — AN IDEA OF YOUR OWN</span><span className="mission-story-edition">HUMAN CURIOSITY / MACHINE PRECISION</span></div><div className="mission-story-title"><h2>Your instinct.<br/><em>Its instructions.</em></h2><p>You bring the idea.<br/>See the rules, set the limits,<br/>and follow the decisions.</p></div><div className="mission-story-workspace"><div className="mission-story-nav" role="tablist" aria-label="Explore an AI mission">{steps.map((s,i)=><button key={s.name} id={'mission-step-'+i} role="tab" aria-selected={active===i} aria-controls="mission-example" onClick={()=>setActive(i)} onKeyDown={e=>{if(['ArrowDown','ArrowRight','ArrowUp','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?2:(active+(['ArrowDown','ArrowRight'].includes(e.key)?1:2))%3;setActive(next);document.getElementById('mission-step-'+next)?.focus()}}} tabIndex={active===i?0:-1}><span>0{i+1}</span>{s.name}<b aria-hidden="true">↗</b></button>)}<Link href="/agents">Build your own mission <span aria-hidden="true">↗</span></Link></div><div id="mission-example" role="tabpanel" aria-labelledby={'mission-step-'+active} className="mission-story-panel" tabIndex={0}><div key={active} className="mission-story-content"><div className="mission-story-meta"><span>{step.label}</span><span>EXAMPLE MISSION</span></div><h3>{step.title}</h3>{active===0?<blockquote>{step.body}<span className="mission-pencil" aria-hidden="true">make it yours.</span></blockquote>:active===1?<div className="mission-rule-sheet"><p>{step.body}</p><div><span>WHEN</span><strong>RSI crosses above 30</strong></div><div><span>THEN</span><strong>Buy with virtual USDT</strong></div><div><span>LIMIT</span><strong>100 USDT per order</strong></div></div>:<div className="mission-trace-sheet"><strong>{step.body}</strong><div><span>Previous RSI</span><b>28.4</b></div><div><span>Latest RSI</span><b>29.1</b></div><div><span>Crossed above 30?</span><b>No → wait</b></div></div>}<p className="mission-story-footnote">{step.foot}</p></div></div></div><div className="mission-story-signoff"><span>YOUR IDEA STAYS YOURS.</span><p>The thinking is there to see.</p><span aria-hidden="true">✳</span></div></section>}
